repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-added-large-files
    - id: check-byte-order-marker
    - id: check-executables-have-shebangs
    - id: forbid-new-submodules
    - id: check-yaml
      exclude: '.clang-format'
    - id: check-json
    - id: pretty-format-json
      args: ['--no-sort-keys']
    - id: check-symlinks
    - id: check-xml
    - id: end-of-file-fixer
      types_or: [c, shell, python, proto]
    - id: trailing-whitespace
      types_or: [c, shell, python, xml]
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: mixed-line-ending
      args: [--fix=lf]

-   repo: https://github.com/ambv/black
    rev: 23.12.1
    hooks:
    - id: black

-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    - id: codespell
      args: [--write-changes]

-   repo: local
    hooks:
    - id: clang-format
      name: clang-format
      entry: clang-format
      language: system
      files: \.(c|cpp|h)$
      args: ["-i"]
